### ISSUE TITLE
[Bug] DateViewer 

### ISSUE THREAD

**Issue by Momo1352** [Arashiryuu/crap#206]
**Which plugin is this about?**
DateViewer

**Describe the Bug**
DateViewer Plugin is causing Settings to open very very  slowly or not at all, on first time open after starting Discord 

**To Reproduce**
open settings after ctrl + R

**Expected Behavior**
Opening Settings as usal

**Screenshots**

**Discord Version**
 Stable

**Additional Context**

**Comment by Arashiryuu** [comment]
Are you sure this is traceable to this plugin? I cannot reproduce it following the provided information.

**Comment by Momo1352** [comment]
For me it only appears with DateViewer, with it the only one in Plugins folder. In combination with other plugins it seems to make settings open even slower or not at all

**Comment by Momo1352** [comment]
https://cdn.discordapp.com/attachments/924294086423375872/1102257774764773376/DateViewer_Bug.mp4

**Comment by Arashiryuu** [comment]
Yeah idk what to tell you, I can't reproduce this problem though my plugin count is much smaller than yours.

I ran a couple profiles over when the settings page is freshly opened after a restart showed me that my plugin had very little performance impact during that time; the actual heaviest part of it is where it uses the native `Date` APIs to generate the time/date/weekday output. Even then, it only adds up to about 157ms or 0.157 of a second at worst.

![DateViewerHeaviest](https://user-images.githubusercontent.com/24483230/235364286-4c8afe15-3451-4e5d-8008-0ac01c023a27.png)

I say "at worst" because the stacks only seemed to attribute ~38ms to my plugin in the most recent profile which I'm taking these images from;

![DateViewerLighter](https://user-images.githubusercontent.com/24483230/235364473-ae04fb3f-7eed-45cd-b160-c811bad7a93d.png)

it may be possible there is a plugin conflict somewhere but at present I'm unaware of any and have no leads as to where the root of the issue may lie.

**Comment by Momo1352** [comment]
Alright, i think ill just have to deal with it. But thanks for ur effort and ur Plugins :D

**Comment by janez33** [comment]
Thank you for fixing DateViewer for us :) I can cofirm the issue is also present for me :)

**Comment by Momo1352** [comment]
Without dateViewer
![image](https://github.com/Arashiryuu/crap/assets/124119932/b11f4bd7-b08f-4f6d-9ae5-bedfe501bd1d)

With DateViewer
![image](https://github.com/Arashiryuu/crap/assets/124119932/829e5597-6627-49fa-88dc-037ee1370db4)


idk if this is usefull

**Comment by Arashiryuu** [comment]
If anything this is showing a counter-statement to the main topic of the thread, since it's saying my plugin took `0.0ms` which is literally no time at all.

**Comment by Arashiryuu** [comment]
@Momo1352 I've just pushed an update which I believe either fixes or largely alleviates this issue.

**Comment by janez33** [comment]
I've tested it but it's still hanging for me.

**Comment by Momo1352** [comment]
sadly same here

**Comment by Momo1352** [comment]
Missclicked
