### ISSUE TITLE
MemberCount plugin broke today

### ISSUE THREAD

**Issue by tryoutuser** [Arashiryuu/crap#27]
The plugin is broken as in today discord unknown changes, and I couldn't start or stop it.

Hope you investigate and update soon, because I find this plugin is very useful to count my server members.

**Comment by just-Addict** [comment]
Sadly todays update (20 Jan) did not fix the issue for me, still getting the following error in the console in Release/PTB/Canary
And yes, Zerebos' Plugin library is installed and activated.

According to Zerebos, this error is caused by referencing a deprecated/discontinued version of the library
![2019-01-20_162152](https://user-images.githubusercontent.com/19715616/51441935-56b8aa80-1cd7-11e9-9691-c5b004e58aa0.png)

**Comment by tryoutuser** [comment]
Will there be a fix to this?
