### ISSUE TITLE
MemberCount shows probably incorrect count

### ISSUE THREAD

**Issue by Huddlect** [Arashiryuu/crap#43]
In large guilds the plugin always shows ~100 members less than DetailedServerTooltips. In small guilds the count of both plugins is the same.

**Comment by Arashiryuu** [comment]
The plugin itself works fine, though I have no idea what's going on over your end for you to think otherwise.
Below is a screenshot I just grabbed of it working on a guild with over 40,000 members, and it still works accurately on guilds with over 90,000 members. No matter the size of the guild, big or small.
![worksFineOver40k](https://user-images.githubusercontent.com/24483230/57706225-400ada80-765d-11e9-8e41-e36a0d3bff07.png)

**Comment by Huddlect** [comment]
Could any other plugin be interferring?

**Comment by Huddlect** [comment]
Ok my bad, someone confirmed that DST's counter is wrong.
